-- ModuleScript: ReplicatedStorage>Modules>MovesModules>WeavePulse
local WeavePulse = {
    id = "WeavePulse",
    name = "Weave Pulse",
    rarity = "Amateur",
    power = 15,
    cooldown = 2.1,
    minRange = 2,
    maxRange = 12,
    castTime = 0.6,
    castSpeed = 1.0,
    lockMovement = true,
    effects = {},
    tags = { "Magic", "Progenitor", "Ranged" },

    accuracy = 0.9,
    mpCost = 6,
}

return WeavePulse
